### ISSUE TITLE
Filebrowser integration

### ISSUE THREAD

**Issue by paolodina** [batiste/django-page-cms#101]
Reading [the docs ](http://pythonhosted.org/django-page-cms/placeholders.html#filebrowseinput) I see that django filebrowser should be supported out of the box using the `FileBrowseInput` widget. I'd need some help to use [file browser no grappelli](https://github.com/smacker/django-filebrowser-no-grappelli/) within the cms. I tried to 1. change the widget of the common placeholder and 2. to create a new placeholder but had no luck with both. This is what I did:

#### 1. Change the widget of the common placeholder
```python
# widgets.py
from filebrowser.fields import FileBrowseWidget
from pages.widgets_registry import register_widget

class FileBrowseCMSWidget(FileBrowseWidget):
    def __init__(self, language=None, attrs=None, **kwargs):
        if attrs is None:
            attrs = {}
        super(FileBrowseCMSWidget, self).__init__(attrs)

register_widget(FileBrowseCMSWidget)
```
```
base_template.html
{% placeholder foobar with FileBrowseCMSWidget %}
```
Exception: http://dpaste.com/2BW3ZB3

#### 2. Create a new placeholder
```python
# filebrowser_placeholders.py
from django import template

from filebrowser.widgets import ClearableFileInput
from filebrowser.fields import FileBrowseWidget, FileBrowseField

from pages.placeholders import PlaceholderNode
from pages.placeholders import parse_placeholder

register = template.Library()

class FileBrowsePlaceholderNode(PlaceholderNode):
    def get_widget(self, page, language, fallback=ClearableFileInput):
        return FileBrowseWidget

def do_filebrowser_placeholder(parser, token):
    name, params = parse_placeholder(parser, token)
    return FileBrowsePlaceholderNode(name, **params)

register.tag('filebrowser_placeholder', FileBrowsePlaceholderNode)
```
```
base_template.html
{% filebrowser_placeholder "foobar" %}
```
Exception: http://dpaste.com/3PYV13H

Was anyone able to use filebrowser with django page cms, and how?

**Comment by remik** [comment]
Is it still invalid and looks like external package error? Can we close?

**Comment by batiste** [comment]
Yes let's close this
