### ISSUE TITLE
Cache wrapper not working properly

### ISSUE THREAD

**Issue by smant** [batiste/django-page-cms#123]
1. Since April 5  PAGE_CACHE_LOCATION setting not used anywere 
2. With Django 1.8.6 code on pages/cache.py always select 'default' cache

1 + 2 + locmem cache as default + several uwsgi workers =  hard to resolve issues with editing

**Comment by remik** [comment]
This one looks bigger as CMS is invalidating cache but at that moment it has access to only 1 cache location.
It need to know when cache was create and update if outdated.

**Comment by batiste** [comment]
The cache has been designed with memcache in mind: a single point of truth for cache. If you are using memory cache in several processes it will not invalidate properly.

**Comment by batiste** [comment]
I updated the documentation and fixed the bug with the cache:

http://django-page-cms.readthedocs.org/en/latest/installation.html#caching
https://github.com/batiste/django-page-cms/commit/e87b3d0b33d5cfd296ae455eb9ba3824502cff44

Thanks for the report. Could you check this is all working? I would like to unit test this but it looks like it might be an difficult task.
