### ISSUE TITLE
Use reverse instead of hardcoded urls

### ISSUE THREAD

**Issue by remik** [batiste/django-page-cms#130]
In many places we are using hardcoded urls (especially in tests) eg. /admin/pages/page/add/
We should use `reverse` function so we don't need update this urls if someone (eg. Django Core) change it.
I Django 1.8 was a change for details page so I update a lot places but few still left.

**Comment by batiste** [comment]
Would you provide a more detailed description of what needs to be done here? I might have time to work on that soon.

**Comment by remik** [comment]
Updated.

**Comment by batiste** [comment]
I have worked on it here: https://github.com/batiste/django-page-cms/commit/1a26f0a673370b71ebe4dc01f1428ff2009211e7

Is it satisfying?

**Comment by remik** [comment]
Yes. Thanks!
