### ISSUE TITLE
AdminTextInput and AdminTextarea not registered widget

### ISSUE THREAD

**Issue by zcho** [batiste/django-page-cms#133]
The code is not implemented.
Mentioned only in the documentation.

**Comment by batiste** [comment]
The documentation was not up to date anymore. This is fixed here:

https://github.com/batiste/django-page-cms/commit/1d57d0310f6b1c10af6fe8e9664f84dc400d75f0

http://django-page-cms.readthedocs.org/en/latest/placeholders.html#admintextinput

Thank you
