### ISSUE TITLE
Cant use pages_navigation outside of cms pages

### ISSUE THREAD

**Issue by rosscdh** [batiste/django-page-cms#134]
Hi there, great cms variation btw. Keen to use it.

I have a problem where; when outside of any cms page, I cannot use the `pages_navigation` templatetag

is this desired behaviour? should I write a custom template tag to work around it or have a missed something?

**Comment by batiste** [comment]
Have you used the {% load_pages %} template tag inside your template?
This is needed so some fundamental variable are loaded in the current context:

https://github.com/batiste/django-page-cms/blob/master/pages/templatetags/pages_tags.py#L358

In short pages_navigation and current_page are the 2 context variables that are expected to be present in the context if you want to use navigation template tag.

**Comment by rosscdh** [comment]
Ah Morning sorry I just noticed this message.

I found exactly that looking through the template_tags code, fantastic :) thanks for the tip!

```
            {% load_pages %}
            {% for page in pages_navigation %}
```

works a charm :)
