### ISSUE TITLE
Minor change - language field max_length issue

### ISSUE THREAD

**Issue by sunjoomoon** [batiste/django-page-cms#138]
../pages/models.py, around line number 500, below
```
    language = models.CharField(_('language'), max_length=5, blank=False)
```
Which could cause issue if >=django 1.8 used with ```zh-hans``` which has 7 characters instead of 5. So, to be safe I set it 10
```
language = models.CharField(_('language'), max_length=10, blank=False)
```

**Comment by sunjoomoon** [comment]
Closing this...  hope to reflect this in the next release

**Comment by batiste** [comment]
Why not creating a pull request for this? I would appreciate your contributions!

**Comment by sunjoomoon** [comment]
Hmm, ok. Let me work around more and get things all together for the pull reuest in due time. Thanks for the awesome works.
