### ISSUE TITLE
Suggestion - Any plan to add meta_description & meta_keyword fields?

### ISSUE THREAD

**Issue by sunjoomoon** [batiste/django-page-cms#139]
Wondered if any plan to add two more fields  - meta_description & meta_keywords for SEO purpose. I had a look around the models.py and could not comfortably figure out how to, just for your info.

**Comment by remik** [comment]
I have a plans to add it. I already have it in my fork but need to migrate it to clean code. 
As usually no time so can't say any ETA.

**Comment by sunjoomoon** [comment]
Cool. Great. Thanks.

**Comment by batiste** [comment]
Also you can very easily just implement that with a placeholder. E.g.:

    <meta name="description" content="{% placeholder meta-description %}">

I would not recommend adding fields to the model when a placeholder field can do the job fine.

**Comment by remik** [comment]
Yes, this is simple way but I want to do something more then just new fields (that's why I didn't copied from my fork). 
Issue with SEO is that there can be a lot of fields and mostly you don't need to see it. I would like to implement some way for grouping and collapsing it.

**Comment by sunjoomoon** [comment]
Yes, that is how I did that and makes sense to leverage the power of placeholder vs. DB.  Learning things one by one now. Awesome experience !
