### ISSUE TITLE
Enlarge RichTextarea

### ISSUE THREAD

**Issue by jpic** [batiste/django-page-cms#147]
Hi !

Thanks a lot for sharing this great app !

How would you suggest to enlarge the RichTextarea widget ?

![2016-06-11-115917_1305x541_scrot](https://cloud.githubusercontent.com/assets/94636/15984465/59bc1f8c-2fcc-11e6-8f2f-cf9709d06cfb.png)

Thanks !

**Comment by batiste** [comment]
This is a good idea. This latest commit should have provided this: https://github.com/batiste/django-page-cms/commit/ab651238f360336b39e96cd3820531efeb864173
