### ISSUE TITLE
Change Page - View on site bug?

### ISSUE THREAD

**Issue by kayadata** [batiste/django-page-cms#159]
Hi guys. 
i installed with  "pip install django-page-cms[full]; gerbi --create mywebsite"
In change page view. After changing language "View On Site" doesnt work for other languages but default language.

**Comment by batiste** [comment]
You are correct. The "view on page" on in the page edit interface doesn't honor the current edited language. I will see if can something about that.

**Comment by batiste** [comment]
This latest commit fixes this issue

https://github.com/batiste/django-page-cms/commit/f7c065960ea5dcd7003ba087d696bb665cf98b7f
