### ISSUE TITLE
General Settings for Pages. 

### ISSUE THREAD

**Issue by kayadata** [batiste/django-page-cms#163]
Hi. Im loving this cms.

Currently im doing a setting.html and make it draft. So i can pull placeholders from there to display like footer social and stuff. . But is there a better option for this ? 
Can i hide the placeholder at homepage and edit there to use it at another template.

**Comment by batiste** [comment]
Hi,

Thank you for your kind words. I think what you do sounds fine. You can "hide" the placehoder by useing the "as" option. You could also consider using the inheritance option mechanisms although this is not very flexible.

https://pythonhosted.org/django-page-cms/placeholders.html#the-inherited-keyword

If you want placeholder with content completely disconnected from the Page object I believe that would be a good candidate for a contribution. First step would be to subclass the Placeholder and redefine the get_content so it gets its content from some other model?

The the discussion would be about what this model would look like? How do you present it in the admin interface? Is it still translatable content? There is several question that need to be answered and a bit of admin work. But it is totally feasible if you are familiar with Django and I would gladly help and accept the contribution and add your name to the author file of this CMS.

Tell me what you think,

Cheers,
Batiste

**Comment by kayadata** [comment]
Hello there. I'm sorry for the late reply. I added it to "Homepage" as you said, and hid it in the template with the command "as". This use is good for me for now. At least it's better than mine.

As for the other things you say. I just started learning Django. But i'm quick learner. From now on I am starting to use Django and this CMS for my clients. And after i've completely mastered django, you can be sure that I will support this project.

But for now something like this can be done:

We create "settings" or something similar command. And using this in the template, the content that is the same on every page can be edited only in the general settings section.

I mean,

 {% Placeholder "Facebook" settings section "Social Media"%}
 {% Placeholder "Twitter" settings section "Social Media"%}

 {% Placeholder "Google" settings section "Search Analytics"%}
 {% Placeholder "Bing" settings section "Search Analytics"%}

The above sections will only be shown in the general settings section. And we show it in base.html because it will be the same content on every page.

Best regards,
Kaya

**Comment by batiste** [comment]
Hi,

I just implemented a feature that should in fact solve the use case you had. Have a look here:

http://django-page-cms.readthedocs.io/en/latest/placeholders.html#the-shared-keyword

**Comment by kayadata** [comment]
Hi batiste,

I'm sorry for the late reply. I was out of town.

Thanks for the feature. But I'm having performance issues with version 1.9.9. Even the admin page is loading slow. I had to downgrade it to version 1.9.6. There is no problem now.

I used only 20 placeholders on a theme. You can test too.

By the way, do you intend to open the google group for app support?

Thanks again for all the efforts you put into this cms.

**Comment by batiste** [comment]
Thanks kayadata. It is totally possible that the latest changes will create very slow template rendering. I already know what is the issue and it is not related to the "shared" feature.

I will try to fix that in the incoming week.

**Comment by batiste** [comment]
@kayadata I just made a new release (1.9.10) that should fix the performance issue. Thanks for pointing it out to me there was a problem with 1.9.9.

**Comment by kayadata** [comment]
Hello, @Batiste,

Thanks for the quick upgrade, but now I think the "endplaceholder" tag is broken.

Besides, there are a few more mistakes as far as I can see. If you want, I can create a new issue for them. These are:

<Meta name = "description" content = "{% placeholder" meta_description "section" SEO "%}" /> etc. It is not working anymore.

It looks like this.
<Meta name = "description" content = "Description <! - placeholder; meta_description; ->">

This error is related to the new inline editing feature.

{% Placeholder "footer-links" shared%} I have not managed to run it somehow.
I added it to base.html and footer.html, but they do not appear in the admin panel.

If you accept. I've also seen a few bugs that I can fix, and I will commit them if I am available this week.

Thanks again.

**Comment by batiste** [comment]
@kayadata a quick note on the placeholder block. It is now necessary to mark a placeholder as a block like so:

    {% placeholder "something" block %}
    {% endplaceholder %}

You are more than welcome to make pull requests and fix bugs off course.

**Comment by batiste** [comment]
Another note: the magic comment that appears are part of the inline edit system. They only apear if you are logged in as a staff user. Normal users or Google will not see them.

I could also make things work a bit differently if this comment is really a problem, like having a way to disable edit mode. That one should be rather easy to do.
