### ISSUE TITLE
child nodelist is None

### ISSUE THREAD

**Issue by karyon** [batiste/django-page-cms#170]
Hi!

I'm maintaining django-compressor and we had this issue here: https://github.com/django-compressor/django-compressor/pull/825. The question is whether django-compressor should handle such a child nodelist (to be honest, I'm not even sure what that is, I don't know that part of the code well) being None or whether that's a bug in django-page-cms. Could you shed some light on this? Unfortunately, it is not clear where the None value is produced.

(fwiw, sorl-thumbnail creates a None nodelist as well: https://github.com/django-compressor/django-compressor/pull/605)

**Comment by batiste** [comment]
The issue if fixed in 1.9.17
