### ISSUE TITLE
NameError: global name 'Http404' is not defined

### ISSUE THREAD

**Issue by danielsokolowski** [batiste/django-page-cms#57]
When attempting to use the sample cool template the following trace stack happens ad infinitum: 

[Sat Apr 07 00:44:22 2012] [error] ERROR Internal Server Error: /admin/pages/page/2/template/images/portfolio/ventilationchamber_thumb.jpg/
[Sat Apr 07 00:44:22 2012] [error] Traceback (most recent call last):
[Sat Apr 07 00:44:22 2012] [error]   File "/srv/www/django/webdesign.danols.com/virtualenv/src/django/django/core/handlers/base.py", line 111, in get_response
[Sat Apr 07 00:44:22 2012] [error]     response = callback(request, _callback_args, *_callback_kwargs)
[Sat Apr 07 00:44:22 2012] [error]   File "/srv/www/django/webdesign.danols.com/virtualenv/src/django/django/contrib/admin/options.py", line 368, in wrapper
[Sat Apr 07 00:44:22 2012] [error]     return self.admin_site.admin_view(view)(_args, *_kwargs)
[Sat Apr 07 00:44:22 2012] [error]   File "/srv/www/django/webdesign.danols.com/virtualenv/src/django/django/utils/decorators.py", line 91, in _wrapped_view
[Sat Apr 07 00:44:22 2012] [error]     response = view_func(request, _args, *_kwargs)
[Sat Apr 07 00:44:22 2012] [error]   File "/srv/www/django/webdesign.danols.com/virtualenv/src/django/django/views/decorators/cache.py", line 88, in _wrapped_view_func
[Sat Apr 07 00:44:22 2012] [error]     response = view_func(request, _args, *_kwargs)
[Sat Apr 07 00:44:22 2012] [error]   File "/srv/www/django/webdesign.danols.com/virtualenv/src/django/django/contrib/admin/sites.py", line 192, in inner
[Sat Apr 07 00:44:22 2012] [error]     return view(request, _args, *_kwargs)
[Sat Apr 07 00:44:22 2012] [error]   File "/srv/www/django/webdesign.danols.com/virtualenv/lib/python2.6/site-packages/pages/admin/__init__.py", line 263, in change_view
[Sat Apr 07 00:44:22 2012] [error]     raise Http404('The "%s" part of the location is invalid.'
[Sat Apr 07 00:44:22 2012] [error] NameError: global name 'Http404' is not defined

**Comment by AtulKaushik** [comment]
use following import in views.py
from django.http import HttpResponse, Http404
